model_name: buffalo_l
output_root: output
qdrant_collection_name: face_embeddings

image_paths:
  - "C:\\Users\\SHO\\Pictures\\D-days\\50-days"
  - "C:\\Users\\SHO\\Pictures\\D-days\\50-days"
  - "C:\\Users\\SHO\\Pictures\\D-days\\adama"
  - "C:\\Users\\SHO\\Pictures\\D-days\\culture day"
  - "C:\\Users\\SHO\\Pictures\\D-days\\grad"
  - "C:\\Users\\SHO\\Pictures\\D-days\\jema"
  - "C:\\Users\\SHO\\Pictures\\D-days\\kuriftu"
  - "C:\\Users\\SHO\\Pictures\\D-days\\mechanical+yub"
  - "C:\\Users\\SHO\\Pictures\\D-days\\oldies"
  - "C:\\Users\\SHO\\Pictures\\D-days\\photo shoot"
